### ISSUE TITLE
Renamed Project

### ISSUE THREAD

**Issue by CreativeCodeCat** [XDream8/dreamsrepo#1]
hey mate [wm-maim](https://github.com/XDream8/dreamsrepo/tree/master/x11-misc/wm-maim) has become [win-shot](https://github.com/the-repo-club/win-shot)

**Comment by XDream8** [comment]
thanks for informing

**Comment by CreativeCodeCat** [comment]
hey dude are you still using repowm as I'm planing to redo alot of it as it seems to have broken on arch Linux after an update and I'm too lazy to fix it so I plan to start again on it :)

**Comment by XDream8** [comment]
Yeah i use repowm time to time. If you require any help at all just ask me

**Comment by CreativeCodeCat** [comment]
I think the issue with it crashing has to do with the autostart.sh part aka runAutoStart() function I'll have a look and see

**Comment by XDream8** [comment]
Is it still continues to crash on arch? I will update to latest release and see.

**Comment by XDream8** [comment]
Do you still use matrix or telegram so we can message each other easily

**Comment by CreativeCodeCat** [comment]
I don't and no the new build that I just redid minus the press mod+space message and I moved the power and menu to be custom launchers and icons works fine now :)

**Comment by CreativeCodeCat** [comment]
I do have IRC TheRepoClub at libera.chat
